#!/bin/bash

alias syncjekyll='rsync -avzh --progress --rsh='"'ssh -p42'"' --no-p --delete --exclude=stats --exclude=.DS_Store /Users/seananderson/Dropbox/seananderson.github.com/_site/ sean@173.230.131.228:/home/sean/public_html/'
